language: node_js
node_js: lts/*
sudo: required
addons:
  firefox: latest
  chrome: stable
before_script:
  - npm install -g polymer-cli
  - npm install
script: xvfb-run polymer test --module-resolution=node --npm

